version: '3'
services:
  ps16-web:
    image: openpresta/prestashop:1.6.1.x-php7.2
    ports:
      - 8016:80
    volumes:
      - ./ps16-logs:/var/log/apache2
      - ps16-config:/var/www/html/config

  ps16-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_password
      MYSQL_ROOT_PASSWORD: ps_root
    volumes:
      - ps16-db-data:/var/lib/mysql
    ports:
      - 3416:3306

  ps17-web:
    depends_on:
      - ps17-database
    image: openpresta/prestashop:1.7.5.x-php7.2-debug
    ports:
      - 8017:80
    environment:
      XDEBUG_REMOTE_HOST: 0.0.0.0
    volumes:
      - ./ps17-logs:/var/log/apache2:delegated
      - ps17-config:/var/www/html/app/config:cached
      - ps17-modules:/var/www/html/modules:cached
      - ps17-images:/var/www/html/img:cached

  ps17-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_password
      MYSQL_ROOT_PASSWORD: ps_root
    volumes:
      - ps17-db-data:/var/lib/mysql
    ports:
      - 3417:3306

volumes:
  ps16-config: ~
  ps16-db-data: ~
  ps17-config: ~
  ps17-db-data: ~
  ps17-modules: ~
  ps17-images: ~
