version: '3'
services:
  web:
    image: openpresta/prestashop:1.6.1.x-php7.2
    ports:
      - 8016:80
    volumes:
      - ./logs:/var/log/apache2
      - config:/var/www/html/config
      - ./modules:/var/www/html/modules

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_password
      MYSQL_ROOT_PASSWORD: ps_root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  config: ~
  db-data: ~