version: '3'
services:
  ps16-web:
    image: openpresta/prestashop:1.6.1.x-php7.2
    ports:
      - 8016:80
    volumes:
      - ./ps16-logs:/var/log/apache2
      - ps16-config:/var/www/html/config

  ps16-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_password
      MYSQL_ROOT_PASSWORD: ps_root
    volumes:
      - ps16-db-data:/var/lib/mysql
    ports:
      - 3416:3306

  ps17-web:
    image: openpresta/prestashop:1.7.5.x-php7.2-debug
    ports:
      - 8017:80
    volumes:
      - ./ps17-logs:/var/log/apache2
      - ps17-config:/var/www/html/app/config
    environment:
      HOSTNAME: localhost
      DB_HOST: ps17-database:3306
      DB_NAME: prestashop
      DB_USER: ps_user
      DB_PASSWORD: ps_password
      EMAIL: john.doe@example.com
      PASSWORD: qwerty12345
      SHOP_NAME: "Prestashop 1.7 Developer Demo Store"
      LANGUAGE: en

  ps17-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ps_user
      MYSQL_PASSWORD: ps_password
      MYSQL_ROOT_PASSWORD: ps_root
    volumes:
      - ps17-db-data:/var/lib/mysql
    ports:
      - 3417:3306

volumes:
  ps16-config: ~
  ps16-db-data: ~
  ps17-config: ~
  ps17-db-data: ~
